# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    app.kubernetes.io/name: redis
spec:
  ports:
    - name: redis
      port: 6379
  clusterIP: None
  selector:
    app: redis
---
# Client service for connecting to any redis instance for reads.
# For writes, you must instead connect to the primary: redis-0.redis.
apiVersion: v1
kind: Service
metadata:
  name: redis-read
  labels:
    app: redis
    app.kubernetes.io/name: redis
    readonly: "true"
spec:
  ports:
    - name: redis
      port: 6379
  selector:
    app: redis
