# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"
    config.vm.hostname = "single"
    config.vm.network "private_network", ip: "192.168.33.80"
    config.vm.synced_folder "./code", "/vagrant_data"
    config.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.memory = "8024"
        vb.cpus = 4
        vb.name = "single"
    end
end
