apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-in-kubernetes-cli
  labels:
    tier: backend
    layer: cli
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend
      layer: cli
  template:
    metadata:
      labels:
        tier: backend
        layer: cli
    spec:
      containers:
        - name: cli
          image: laravel-in-kubernetes/composer_base
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: laravel-in-kubernetes
            - secretRef:
                name: laravel-in-kubernetes