# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"
    config.vm.hostname = "worker01"
    config.vm.network "private_network", ip: "192.168.33.71"
    config.vm.synced_folder "./code", "/vagrant_data"
    config.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "8024"
        vb.cpus = 4
        vb.name = "worker01"
    end
end
